### ISSUE TITLE
Create and upload a snapshot when a file changes in a magic-folder

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#107]
When a file is modified this should be recorded in the snapshot DAG with a new tip snapshot and a content reference pointing to the new content.

**Comment by meejah** [comment]
A design exists now: https://docs.google.com/document/d/1c-eIE4U7Yi9NQmjGbrYtqsyirxztjfYcq78V7YiSLEY/edit#heading=h.8jccrvt1krff

**Comment by meejah** [comment]
(After pasting that link it occurs to me that the result of the "lightweight design templates" should maybe be a `docs/proposed/<something-relevant>.rst` ...)

**Comment by exarkun** [comment]
> A design exists now: https://docs.google.com/document/d/1c-eIE4U7Yi9NQmjGbrYtqsyirxztjfYcq78V7YiSLEY/edit#heading=h.8jccrvt1krff

I think that might be the wrong google doc link anyhow.

**Comment by meejah** [comment]
Ah yes, sorry this one: https://docs.google.com/document/d/1boIlM93JLR2ZoaKvCjCdU6IEkfeHFv20xUwdNWReaRk/edit

**Comment by meejah** [comment]
(@exarkun noticed an error in the doc link so I'm deleting both his and my comment that both contain the incorrect link)

**Comment by meejah** [comment]
the scanner ref'd in the doc is implemented
