### ISSUE TITLE
Snapshot metadata includes a creation timestamp

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#112]
Snapshots should include a timestamp reflecting their creation time.

A suggested format for this is UTC time represented as POSIX time (seconds since epoch) but an alternate format to consider is ISO8601 datetime.

**Comment by meejah** [comment]
will be fixed by #442

**Comment by meejah** [comment]
Snapshots include metadata for mtime and ctime (as epoch-seconds timestamps).
