### ISSUE TITLE
 download of files based on snapshots

### ISSUE THREAD

**Issue by vu3rdd** [LeastAuthority/magic-folder#128]
With snapshots, each client would periodically scan each other's DMD and download the snapshots (until it finds its own current snapshot by walking up through the DAG).

**Comment by meejah** [comment]
This process will mirror the "upload" side, with two main parts:
- decide what to download
- download and cache and RemoteSnapshots we don't already have

The last bit can be viewed as recursive: if we just downloaded a RemoteSnapshot we should make sure we have all of its parents. If we don't, they need to be downloaded as well. The "decide what to download" comes from reading each other participant's DMD .. and the list of participants is sync'd from the remote DMDs.
