### ISSUE TITLE
On Windows 10, leaving a magic-folder always fails to remove that folder's sqlite database

### ISSUE THREAD

**Issue by crwood** [LeastAuthority/magic-folder#131]
On Windows 10 (Enterprise Evaluation edition; Build 18362.19h1_release.190318-1202) when I use `magic-folder leave` to leave a given folder, I've noticed that that folder's corresponding sqlite database (located at, e.g., `$nodedir/private/magicfolder_documents.sqlite`) is not being deleted, due, apparently to the db file being still in use:

```
>>> Warning: unable to remove 'C:\Users\User\.tahoe\private\magicfolder_documents.sqlite` due to WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'\\\\?\\C:\\Users\\User\\.tahoe\\private\\magicfolder_documents.sqlite'
```

This happens consistently and constitutes a mild annoyance (since users will always need to manually remove that database file, e.g., in order to re-create or re-join a magic-folder of the same name later) and/or a privacy risk (since this database contains a record of magic-folder changes/activity _including the capabilities for previously deleted files_).

For what it's worth, I have not been able to reproduce this issue on Linux or macOS (where leaving a magic-folder successfully deletes the corresponding sqlite database); this appears to be a Windows-specific mechanism that's preventing the database file lock from being released.

A few other caveats/notes:

I've only observed/tested this using the magic-folder implementation that is still present in Tahoe-LAFS version 1.14.0 (@exarkun has suggested filing this bug here, however -- instead of on the tahoe-lafs.org Trac instance, presumably, because magic-folder has already been removed from Tahoe-LAFS).

I've only observed/tested this using standalone `tahoe` executables that were generated/frozen by PyInstaller. More testing is needed to determine whether this makes any difference.

@burningserenity -- who originally discovered this issue -- tells me that this behavior does not occur on "older versions of Windows 10" (which includes Windows 10 2015 LTSB). I can confirm, at least, that this warning/behavior is a somewhat recent phenomenon (as I've been able to successfully `leave` magic-folders on Windows 10 on numerous occasions within the last year without ever having seen the warning until now).

**Comment by meejah** [comment]
Does this still happen now?

**Comment by crwood** [comment]
It appears not: I just tested Magic-Folder 22.1.0 against the latest version of Windows 10 and was no longer able to reproduce the error message reported above. Granted, the directory structure _is_ a little different now (insofar as each magic-folder's sqlite database is now tucked under a corresponding `folder-SOMEBASE64STRING` subdirectory) but the appropriate configuration (sub)directories are indeed being deleted after a successful leave now).
