### ISSUE TITLE
eliot.twisted.inline_callbacks is required for proper context management

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#134]
A function like:

```
@twisted.internet.defer.inlineCallbacks
def foo():
    with start_action(...):
        yield a()
        yield b()
```

will call `a` in the action context but then leak that same action context out to its caller.

This limitation is addressed by `eliot.twisted.inline_callbacks` which is used exactly like `inlineCallbacks`:

```
@eliot.twisted.inline_callbacks
def foo():
    with start_action(...):
        yield a()
        yield b()
```

Here's an example program to play with:

```
from sys import stdout
from twisted.internet import reactor
from twisted.internet.defer import inlineCallbacks, gatherResults
from twisted.internet.task import deferLater, react
from eliot.twisted import inline_callbacks
from eliot import to_file, Message, start_action

@inline_callbacks
def foo():
    with start_action(action_type=u"foo"):
        yield a()
        yield b()

@inline_callbacks
def bar():
    with start_action(action_type=u"bar"):
        yield a()
        yield b()

def a():
    Message.log(message_type=u"a")
    return deferLater(reactor, 0.0, lambda: None)

def b():
    Message.log(message_type=u"b")
    return deferLater(reactor, 0.0, lambda: None)

def main(reactor):
    to_file(stdout)
    return gatherResults([foo(), bar()])

react(main, ())
```

As written, using `inline_callbacks`, we see a nice action tree:

```
$ python eliot-demo.py  | eliot-tree
e9a31e88-8731-4b2a-be3d-5ae931803a61
└── foo/1 ⇒ started 2020-06-12 13:26:42Z ⧖ 0.001s
    ├── a/2 2020-06-12 13:26:42Z
    ├── b/3 2020-06-12 13:26:42Z
    └── foo/4 ⇒ succeeded 2020-06-12 13:26:42Z

882710c6-f8fc-4420-ba68-51ded357a1e5
└── bar/1 ⇒ started 2020-06-12 13:26:42Z ⧖ 0.000s
    ├── a/2 2020-06-12 13:26:42Z
    ├── b/3 2020-06-12 13:26:42Z
    └── bar/4 ⇒ succeeded 2020-06-12 13:26:42Z
```

If `inlineCallbacks` is used instead, the results get confusing:

```
$ python eliot-demo.py  | eliot-tree 
82b824e5-c95e-414d-a21d-ffe6b0b0e848
└── foo/1 ⇒ started 2020-06-12 13:28:35Z ⧖ 0.001s
    ├── a/2 2020-06-12 13:28:35Z
    ├── bar/3/1 ⇒ started 2020-06-12 13:28:35Z ⧖ 0.000s
    │   ├── a/3/2 2020-06-12 13:28:35Z
    │   ├── b/3/3 2020-06-12 13:28:35Z
    │   ├── b/3/4 2020-06-12 13:28:35Z
    │   └── bar/3/5 ⇒ succeeded 2020-06-12 13:28:35Z
    └── foo/4 ⇒ succeeded 2020-06-12 13:28:35Z
```

Since the context gets a little more out-of-sync with reality with every `inlineCallbacks`-decorated function call, there is a lot of scope for confusing results.

The same problem presumably applies to `pytest_twisted.inlineCallbacks`.  This poses a bit of a problem since the pytest version is required for pytest to work right and the eliot version is required for eliot to work right...

A solution could be to parameterize the *underlying* `inlineCallbacks` to one or both of the others, since they both just wrap the original with a bit of extra logic.

Another solution is manually apply the logic included in one or the other of them - for example, there's also `eliot.twisted.eliot_friendly_generator_function` which I think should compose with `pytest_twisted.inlineCallbacks` so that both libraries are happy.

**Comment by exarkun** [comment]
Indeed, this seems to work:

```
from eliot.twisted import eliot_friendly_generator_function, use_generator_context

use_generator_context()

@inlineCallbacks
@eliot_friendly_generator_function
def foo():
    with start_action(action_type=u"foo"):
        yield a()
        yield b()
```

`use_generator_context` appears to be gone in recent versions of Eliot but it's still in 1.7 which we have to use because it is the last to support Python 2.  When we get to upgrade, I'm not sure if we just get to delete that call or if something more involved is required.

**Comment by meejah** [comment]
This has been normalized as part of Python3: all `@inlineCallbacks` are now `@inline_callbacks`.

The integration test side had to be addressed differently in python3 as pytest no longer "just marks" the test with `@pytest_twisted.inlineCallbacks` so all tests are `async def` and use ensureDeferred which works in `@inline_callbacks`.
