### ISSUE TITLE
"magic-folder migrate" or similar command

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/magic-folder#135]
Currently, magic-folder can load "legacy" config from the Tahoe node-dir. It will *write* config in a slightly new way, but only if you do something to change the config. This sort of magic upgrading doesn't give a good way to provide extra information (e.g. a preferred name) and means other places might have to deal with situations like "missing a Snapshot signing key".

We decided to change this. Desired behavior:

 - if old-style config is encountered (for any magic-folder command), tell the user to run "magic-folder migrate" first
 - add a "magic-folder migrate" (or "magic-folder upgrade"?) that changes old-style config to newer style and updates any missing information (e.g. signing key). It can also have non-optional arguments for any additional information we might need (e.g. "preferred name").

**Comment by meejah** [comment]
This probably falls under the implied questions of "what should we do with all the configuration stuff?" as raised in: https://github.com/LeastAuthority/magic-folder/issues/158

**Comment by meejah** [comment]
(That is, we should decide how magic-folder's configuration is stored before we write a migration command).

**Comment by exarkun** [comment]
I wonder if this really belongs in the OTF milestone.

**Comment by meejah** [comment]
I've also been thinking about whether we even want to support "upgrade from legacy `tahoe magic-folder` at all"? What if the upgrade mechanism was: "create a new magic-folder using the new software and then move all the files you care about into it".

We aren't going to be able to recover "history" from a legacy magic-folder anyway, all we could do with the data is create a new snapshot for everything that currently exists. We *could* import the list of users and so forth from a legacy "collective DMD" too, which might be useful (i.e. save time). However, this would still leave a communication problem: how to get everyone's public keys?

**Comment by meejah** [comment]
This has been implemented and merged as part of https://github.com/LeastAuthority/magic-folder/pull/200
