### ISSUE TITLE
Global option "-d" is not the same as "--node-directory"

### ISSUE THREAD

**Issue by sajith** [LeastAuthority/magic-folder#152]
This is parsed as expected, I believe, although I am not sure about that `Already have a magic-folder named 'default'` message:

```
$ magic-folder --node-directory=alice create test: 
Already have a magic-folder named 'default'
2020-06-24T17:28:14-0400 [twisted.application.runner._runner.Runner#info] Starting reactor...
2020-06-24T17:28:14-0400 [-] Main loop terminated.
```

Perhaps this too:

```
$ magic-folder --node-directory alice create test:
Already have a magic-folder named 'default'
2020-06-24T17:32:28-0400 [twisted.application.runner._runner.Runner#info] Starting reactor...
2020-06-24T17:32:28-0400 [-] Main loop terminated.
```

But this fails:

```
$ magic-folder -d alice create test:
Error: Unknown command: alice

Usage: magic-folder [options] plugin [plugin_options]
Options:
  -V, --version           Display magic-folder version and exit.
      --coverage          Enable coverage measurement.
  -d, --node-directory=   Specify which Tahoe node directory should be used. The
                          directory should contain a full Tahoe node.
      --debug             Print full stack-traces
      --help              Display this help and exit.
  -q, --quiet             Operate silently.
      --version-and-path  Display version numbers and paths to their locations.
Commands:
    create      Create a Magic Folder.
    invite      Invite someone to a Magic Folder.
    join        Join a Magic Folder.
    leave       Leave a Magic Folder.
    list        List Magic Folders configured in this client.
    run         Run the Magic Folders synchronization process.
    status      Display status of uploads/downloads.
Please run e.g. 'magic-folder create --help' for more details on each subcommand.
```

**Comment by meejah** [comment]
Weird. Something else must be grabbing it? I don't really know how Twisted's command-line parsing stuff works. I tried changing it to `-n` and that works ...

**Comment by meejah** [comment]
Oh `-d` is for `--debug` too .. I wonder why Twisted doesn't complain about that?

**Comment by meejah** [comment]
BTW, the "already have a magic-folder named default" is because of the way multiple magic folders was implemented; at some point you could only have a single magic-folder (or zero). Then, "names" were added so you could have multiple magic-folders -- but for backwards compatibility you didn't have to provide the `--name` option .. so if you don't, it uses the name `"default"`.

I think we should re-think the "alias" stuff entirely before a "separate magic-folders" release but that's sort of a separate thing .. but also kind of seems like "a name" so :/

**Comment by sajith** [comment]
Aaah I see.  I was confused by "name" and "alias" and "nickname".  Sounds like the three of them might serve similar purposes?

**Comment by meejah** [comment]
Yeah, and there's also "author". There's definitely a lot of overlap, but: "alias" only exists on clients that created magic-folders (whereas "name" exists on all). Nickname is how the owner names participants. Author is for snapshots (the future!).

I'm hopeful that we can have just two: "name" for the name of the magic-folder and "author" for your name for yourself. If we do participant-management as per Leif's design there is no "Collective DMD" (so no "alias") and there's no "root" / "person who creates the magic-folder" so they don't have to come up with a name for anyone.
