### ISSUE TITLE
Use a default node directory

### ISSUE THREAD

**Issue by sajith** [LeastAuthority/magic-folder#160]
Unless a `--node-directory` is specified, Magic Folder will complain:

```
$ magic-folder run --web-port 8000
Error: Must supply --node-directory (or -n)
```

Perhaps Magic Folder should be using `$HOME/.tahoe` as the default node directory?

Seems that Tahoe is doing more work than just `os.environ.get("HOME") + "/.tahoe"` to find out the default node directory, presumably to handle Windows, so this probably won't be as straightforward as it sounds.

**Comment by meejah** [comment]
Obsolete; we only specify the `--node-directory` when creating a new magic-folder instance.  (Perhaps this could still be a good idea to have in those setup commands but basically "this is config now" and not a general command-line option). Of
