### ISSUE TITLE
A new python API to "manually" trigger an upload

### ISSUE THREAD

**Issue by vu3rdd** [LeastAuthority/magic-folder#161]
In order to simplify testing and overall integration of various pieces of snapshot implementation, it would be nice to have a python function to manually add files to the  upload pipeline instead of using the watchdog/inotify. Internally, watchdog can also rely on the same API to add files to the upload queue and trigger the pipeline.

**Comment by exarkun** [comment]
I think this API would essentially be:

```
POST /v1/magic-folder/<folder name>/files/<relative path>/changed

200 OK
```

The result would be that, for the folder indicated by `<folder name>`, a file that already exists on the filesystem that can be found at `<relative path>` (relative to the folder's local filesystem root) will have a new snapshot created from the filesystem state at that time (or slightly later) and uploaded.

This would be the equivalent to the action we would hope to take when an INotify-based system delivers a CLOSE_WRITE event, presumably.
