### ISSUE TITLE
user "meejahcircleci" needs more permissions

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/magic-folder#187]
I control the github account "meejahcircleci" that is used just for circle-ci stuff (because they don't allow you to NOT give write access to all repositories). However, this user can't re-run jobs for magic-folder. (I get a "do not enter"-style mouse cursor on all things in the "re-run job" drop-down).

**Comment by exarkun** [comment]
I probably have permission to configure this but it's not clear what should be configured. :/  I can't find any CircleCI docs about what permissions are required to gain access to that feature.

So I tried something.  meejahcircleci should have an invite from github waiting.  Please close if that solves the problem.  If not, let me know and I'll find some different buttons to press.

**Comment by meejah** [comment]
`meejahcircleci` still can't re-run jobs. That user also only has its own organization as an option when I log in -- perhaps it needs to be added to LeastAuthority org?
