### ISSUE TITLE
Cooperatively copy content to the stash in `create_snapshot`

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#196]
#141 introduces `create_snapshot` in `magic_folder/snapshot.py`.  In the code beneath the comment marked "2." it reads from a source file and writes to a stash file.  If the stash file is large, this may take a long time.  While this is happening, the magic-folder process is unable to perform other tasks (like reacting to filesystem change notifications or servicing API requests).

An early version of this function was written using `inlineCallbacks` and included a `yield` in the body of the loop.  However, `inlineCallbacks` does not context switch on a bare yield.  Thus the whole file is copied before any context switch can happen.

The smallest code change to address this would be to yield something like `twisted.internet.task.deferLater(reactor, 0.0, lambda: None)` which will allow a context switch (and then resume "very soon").  This may be a good first improvement.  There is room for further improvement, though:

  * `deferLater` after every iteration will be insensitive to the speed of the copying operation.  Compared to a slow disk, a fast disk may be able to do twice as many iterations in the same amount of time but both will suffer the same reactor-turn overhead with this implementation, disproportionately slowing down magic-folder on the system with the faster disk.   
  * `twisted.internet.task.cooperate` may be a solution to this, as it measures the passage of time and makes context switching decisions based on that.
  * However, `cooperate` uses the global reactor which makes it test-unfriendly.  Using it requires jumping through a few extra hoops to be able to write good tests.  The strategy I've used previously is to parameterize `cooperate` itself and then let tests supply their own implementation - either one tied to the test's reactor or one that just consumes the entire task synchronously.  Whether this makes sense here or not may depend on how many layers we have to thread `cooperate` through to reach `create_snapshot`.
  * We may want an even smarter scheduler - for example, one that takes into account new change notifications for files that are in the process of being copied.  If inotify tells us of a new write to a file that's being copied, there's a good chance the in-progress copy is now largely garbage.  We might not want to _unconditionally_ abandon that snapshot but abandoning it in some cases may make sense.

**Comment by meejah** [comment]
I think we should try the simplest thing and then use benchmarks to decide if it's "too slow" and/or quantify any overhead of the `deferLater` solution. We could also allow configuration of the "how much to copy before yielding" parameter to easily compare things. 

(Configuring this from the outset would also make testing deterministic: we would then know how many times to advance a `Clock` for a given amount of data, right?)

**Comment by exarkun** [comment]
> (Configuring this from the outset would also make testing deterministic: we would then know how many times to advance a Clock for a given amount of data, right?)

Cooperator already makes the amount of time it lets pass before switching configurable so we pretty much get this already as soon as we switch to cooperator.  I don't know if Twisted considers the particular value for that interval a stable value that won't be changed in the future but Twisted's value might be too small for us anyway - it uses 0.01 seconds.

> I think we should try the simplest thing

Yes, absolutely, 100% this.  It's only a shame that the simplest thing happens to be so lame even ~15 years after Cooperator was first introduced.

**Comment by meejah** [comment]
> Cooperator already makes the amount of time it lets pass before switching configurable so we pretty much get this already as soon as we switch to cooperator.

...but you said this is test-unfriendly so how does that help when trying to make tests deterministic?

Anyway sounds like the actual action here is: use `yield deferLater(reactor, 0, lambda: None)` after a configurable amount of data is processed. We can benchmark this situation before doing anything more complex.
