### ISSUE TITLE
Add guardrails around handling of the API token

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#202]
#199 added a Bearer token authorization system to the HTTP API.  The implementation merely reads a value from a file on disk.  This value isn't validated or processed in any way to ensure it is usable in the particular area of the HTTP protocol where it is used.

There should be some additional precautions in place here to ensure only valid values can make it past the point where it is initially loaded into the system.

**Comment by meejah** [comment]
What sort of checks are required?

**Comment by meejah** [comment]
To clarify here: the `api_token` file is generated from the database entry upon startup. The token is rotated each startup. It is url-safe base32 encoded from 32 random bytes. I will add checks to the client that the file base32-decodes to 32 bytes but I don't think there's anything else required. (All url-safe base32 characters are valid in HTTP headers).
