### ISSUE TITLE
Add an HTTP API to create a new magic folder

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#210]
Accept a *POST* request to /v1/magic-folder with a JSON-encoded body describing a new magic folder.  Create that folder and return a success response.

eg:

```
POST /v1/magic-folder HTTP/1.1
Content-Type: application/json

{"name": "folder name", "local-path": "absolute local path"}

200 OK

```

**Comment by meejah** [comment]
This will also need an `author-name` as well (and should optionally accept `poll-interval` to be in line with the CLI).

**Comment by meejah** [comment]
hey, I assigned @tomprince because I believe you're already working on this; if not please unassign yourself :)
