### ISSUE TITLE
Magic folder HTTP API key confusion

### ISSUE THREAD

**Issue by sajith** [LeastAuthority/magic-folder#224]
I did a `magic-folder migrate`, and then restarted things:

```
$ magic-folder migrate -n /path/to/nodes/alice/ --listen-endpoint tcp:6001 --author-name alice
$ tahoe run /path/to/nodes/alice/
$ magic-folder -n /path/to/nodes/alice/ run --web-port tcp:6001
```

When making API calls, the token stored in  `~/.config/magic-folder/api_token` does not work (using [httpie](https://httpie.org)):

```
$ http :6001/v1/magic-folder authorization:"Bearer $(cat ~/.config/magic-folder/api_token)"
HTTP/1.1 401 Unauthorized
Content-Length: 0
Date: Mon, 03 Aug 2020 02:52:26 GMT
Server: TwistedWeb/20.3.0
```

But the one stored in `/path/to/nodes/alice/private/api_auth_token` works:

```
$ http :6001/v1/magic-folder authorization:"Bearer $(cat /path/to/nodes/alice/private/api_auth_token)"
HTTP/1.1 200 OK
Content-Length: 156
Content-Type: application/json
Date: Mon, 03 Aug 2020 03:00:13 GMT
Server: TwistedWeb/20.3.0

{
    "folders": [
        {
            "local-path": "/home/sajith/Documents/Shared",
            "name": "shared"
        },
        {
            "local-path": "/home/sajith/Documents/test",
            "name": "test"
        }
    ]
}
```
Looks like API key is read in `MagicFolderService` here:

https://github.com/LeastAuthority/magic-folder/blob/3bf6cbc70c6dac77952469ff32408d3856c947fd/src/magic_folder/cli.py#L691-L695

Which does this:

https://github.com/LeastAuthority/magic-folder/blob/3bf6cbc70c6dac77952469ff32408d3856c947fd/src/magic_folder/cli.py#L711-L712

But that is the wrong key to use after migration, right?  Or maybe there shouldn't be two different keys?

(#207 depends on this.)

**Comment by meejah** [comment]
There is an `api_client_endpoint` and `api_token` file available for clients to read now.
