### ISSUE TITLE
There are two ways to get base URL

### ISSUE THREAD

**Issue by sajith** [LeastAuthority/magic-folder#231]
After #223 has been merged, Magic Folder has two ways to get the base URL for HTTP API:

 * By reading the file `/path/to/taho-node/magic-folder.url`
 * By calling `endpoint_description_to_http_api_root(api_endpoint)`

One of them is possibly redundant, and therefore a source of confusion.

(This is similar to #224, maybe?)

**Comment by meejah** [comment]
Does this confusion still exist now that #216 is merged? Anything at all from `tahoe-node` directory is only for Tahoe to use (and so if it has a `magic-folder.url` that's a "legacy" magic folder of `tahoe magic-folder *` type).

I will split the part of #207 that adds an explicit "client endpoint" out so then there will only be one way: ask the config for the client-endpoint.

**Comment by meejah** [comment]
The client API endpoint stuff was merged in https://github.com/LeastAuthority/magic-folder/pull/252 so I think this confusion should no longer exist. (If it does, please re-open).
