### ISSUE TITLE
Command described in ~/.config/magic-folder/README does not work

### ISSUE THREAD

**Issue by sajith** [LeastAuthority/magic-folder#234]
After `magic-folder migrate` is run, `~/.config/magic-folder/README` says:

```
This is a Magic Folder daemon configuration

To find out more you can run a command like:

    magic-folder --config /home/sajith/.config/magic-folder --help
```

But that command does not work:

```ShellSession
$ magic-folder --config /home/sajith/.config/magic-folder --help
Error: option --config not recognized

```

**Comment by meejah** [comment]
Should  be fixed by #216

**Comment by sajith** [comment]
Tried the #217 PR branch, which fixes #216.  Seems that it hasn't landed yet?

```console
$ magic-folder --config /home/sajith/.config/magic-folder --help
Error: option --config not recognized
$ magic-folder --help --config /home/sajith/.config/magic-folder
Error: option --config not recognized
```

If I understand correctly, `--config` is meant to become a global option, with an appropriate default, rather than a subcommand option.  Is that correct?  If so, that would help me in solving a related issue (#224) and with a PR (#233). :-)

**Comment by meejah** [comment]
Yes, `--config` will basically replace `--node-directory` in "all" the commands 

(And yeah, the original code was loading the API key from the tahoe-lafs config directory .. so it would be the same as the one Tahoe was using for its API which .. isn't great and might have problems e.g. when Tahoe decides to rotate it).

**Comment by meejah** [comment]
This works now for me. Please re-open if not.
