### ISSUE TITLE
There is an unworkable mixing of Magic-Folder "magic directory" and the relative part of contained files

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#284]
Consider a "magic directory" of `/foo` and a contained file with an absolute path of `/foo/bar`.

* The local snapshot is recorded in the config database with a name like "@_foo@_bar".
* It is uploaded to Tahoe-LAFS and linked into the DMD with the same name.
* The remote snapshot is recorded in the config database with the same name.

This lets a single Magic-Folder client keep track of the file and make sense of what's going on.  However, any client that doesn't use `/foo` as the "magic directory" can make no sense of this.

The "name" associated with all of these things must be `bar` instead.  This will let each Magic-Folder client consider the state independent of the "magic directory" of the client which created or modified the file.

**Comment by meejah** [comment]
fixed via https://github.com/LeastAuthority/magic-folder/pull/368
