### ISSUE TITLE
Integration test for file addition into the magic folder

### ISSUE THREAD

**Issue by vu3rdd** [LeastAuthority/magic-folder#291]
Now that https://github.com/LeastAuthority/magic-folder/issues/109 is more or less complete with an HTTP API, it would be possible to write an integration test. Perhaps a way to do that would be:

- create a new magic-folder for user `alice`.
- add a file into the file system directory configured as the "sync folder".
- get `alice`'s upload dircap from the config and read it via `tahoe ls` command for existence of the file and read its properties and check against the original.

**Comment by exarkun** [comment]
Thanks.  See also https://github.com/LeastAuthority/magic-folder/issues/292 which this inspired.

**Comment by meejah** [comment]
There are several tests, including integration tests, that put data in and synchronize it to other users.
