### ISSUE TITLE
cryptography deprecation warning

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/magic-folder#305]
Several integration tests are failing because cryptography > 3.0 issues warnings for Python2 being end-of-lifed. As these are printed to the console by default, the CLI commands no longer interact properly.

**Comment by meejah** [comment]
(To be clear, this is a bug for other users too not just integration-tests)

**Comment by exarkun** [comment]
I failed to reproduce this.  Which tests?  What kind of Python environment?

What I did observe is that pyOpenSSL 20.0.1 is not compatible with cryptography 2.9.2.  Downgrading to pyOpenSSL 19.1.0 in my local virtualenv gives me a fully passing test suite.

**Comment by meejah** [comment]
If I install master in a local 2.7 venv, running `magic-folder` produces this (I have python 2.7.16):

```
(venv) meejah@buyan:~/work/leastauthority/src/magic-folder$ magic-folder 
/home/meejah/work/leastauthority/src/magic-folder/venv/lib/python2.7/site-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
```

**Comment by exarkun** [comment]
Okay.  I can't reproduce that either.  Perhaps this doesn't affect master with the dependencies declared in master - instead it affects master with an upgraded cryptography?  That seems consistent with the info here - master requires cryptography <3.0 and this issue description says the deprecation is about cryptography > 3.0.

**Comment by exarkun** [comment]
But I can't actually run master with cryptography > 3.0 because `pkg_resources` gets angry:

> pkg_resources.DistributionNotFound: The 'cryptography<3.0' distribution was not found and is required by magic-folder
