### ISSUE TITLE
test_web should use `create_testing_configuration` instead of `create_global_configuration`

### ISSUE THREAD

**Issue by tomprince** [LeastAuthority/magic-folder#333]
That way, and in-memory database is used for the global configuration.

(Unfortunately, `ListMagicFolderTests` uses `load_global_configuration` to access the created configuration, otherwise this could be a trivial replacement)

**Comment by meejah** [comment]
This just got fixed, right?

**Comment by tomprince** [comment]
> This just got fixed, right?

No. I fixed the cli tests, but not the web tests. `test_list_folders` still does `load_global_configuration`.

**Comment by tomprince** [comment]
This was fixed in #468.
