### ISSUE TITLE
HTTP API organization

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/magic-folder#359]
See https://github.com/LeastAuthority/magic-folder/pull/332#discussion_r638115777 

This brings up a question about how to organize the HTTP API; currently there are the following endpoints:

-  `/v1/magic-folder` which response to GET and lists (all) magic-folders and their config
- `/v1/snapshot` which responds to GET and lists all snapshots in all folders
- `/v1/snapshot/<folder-name>`  which responds to POST and adds a snapshot

The comment ref'd above is for a PR which adds a `/v1/participants/<folder-name>` API which essentially follows the "snapshot" pattern.

However, maybe it makes more sense to hang some of those APIs behind a `/<folder-name>/` path piece. That is, like: `/v1/magic-folder/<folder-name>/participants` or similar.

**Comment by exarkun** [comment]
`/v1/snapshot` exists because GridSync wants to get all snapshots regardless of which folder they belong to in some cases (at least, it did at one point.  Maybe @crwood can confirm or deny that this is still the case).

I'm not aware of a similar requirement for listing all participants that exist regardless of which folder they are participating in.  So they is no easy-of-use/efficiency argument for having a top-level list of all known participants - at least not yet.

How do participants work in the implementation, though?  Are they confined to a single magic-folder?  Can a snapshot signed by a participant known via folder A ever appear in folder B?  Are there security considerations for such a case?

**Comment by meejah** [comment]
Participants belong to a magic-folder, period. The only way to know them is to list the Collective DMD.

There's nothing preventing someone re-using a private-key on multiple folders .. but also we don't do anything with signatures currently anyway (see e.g. #331). As for a whole Snapshot appearing in two folders: that should never happen .. although we don't do anything to check / prevent that.

The main question here I guess is: should we hang APIs that "definitely need a particular magic-folder" below `/v1/magic-folder/<folder-name>` or shape them like the Snapshot API? I think if we decide the former, we should also move the "create a new snapshot" API to `/v1/magic-folder/<folder-name>/snapshot` for consistency.

So the two choices appear to be:

- `/v1/magic-folder/<folder-name>/participants` (GET to list, POST to create)
- `/v1/magic-folder/<folder-name>/snapshot` (POST to create new snapshot)

OR

- `/v1/snapshot/<folder-name>` (POST to create a new snapshot)
- `/v1/participants/<folder-name>` (GET to list, POST to make a new one)

And I guess any future APIs should follow the pattern, too (that is, if it needs a particular magic-folder, then it goes below `/v1/magic-folder/<folder-name>/...`

**Comment by meejah** [comment]
I think I prefer the `/v1/magic-folder/<folder-name>/...` version where we put all things requiring a magic-folder below that.

**Comment by exarkun** [comment]
> Participants belong to a magic-folder, period. The only way to know them is to list the Collective DMD.
> ...
> /v1/magic-folder/<folder-name>/participants (GET to list, POST to create)
> /v1/magic-folder/<folder-name>/snapshot (POST to create new snapshot)

Sounds like this is the better option.

**Comment by meejah** [comment]
Pretty minor, but maybe then `/v1/snapshot` should be `/v1/all_snapshots` or something to avoid confusion with the other API? (And `/v1/magic-folder/<folder-name>/snapshot` could respond to GET in the future if GridSync or something else needs "all snapshots from one folder")

**Comment by sajith** [comment]
I think convention is to use plurals (`snapshots`) for all items in a collection, and then `snapshots/<id>` for specific items.

**Comment by meejah** [comment]
> I think convention is to use plurals (snapshots) for all items in a collection, and then snapshots/<id> for specific items.

Okay, we could use `/v1/snapshots` (GET == all snapshots) and `/v1/magic-folder/<folder-name>/snapshot` (POST == create snapshot) for sure .. was just wondering if the `s` is enough differentiator but also this isn't UI for the user, so meh ;)
