### ISSUE TITLE
magic folders can't be named `.`, `..`, `README`, `api_token`, or `global.sqlite`.

### ISSUE THREAD

**Issue by tomprince** [LeastAuthority/magic-folder#369]
This is because the name of folder is used as a sub-directory of the configuration folder.

**Comment by meejah** [comment]
Hmm, yeah the `README` and other ones seem like weird limitations to have; what if we put the folder configs under `./folders/` or similar?

(Excluding `.` and `..` seems reasonable)

**Comment by tomprince** [comment]
Thinking about this some more; if we are running on windows, we can't use any of `/\:\"?<>|` or have trailing `.` either.

**Comment by exarkun** [comment]
> Thinking about this some more; if we are running on windows, we can't use any of `/\:\"?<>|` or have trailing `.` either.

Also CON, PRN, LPT1, etc. :)

**Comment by meejah** [comment]
Hmm, does that mean we maybe need like UUIDs ("or something" .. truncated sha256 of the name?) for folder-directories and map folder-names -> those in the database?
