### ISSUE TITLE
Make non-ASCII paths work

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#38]
There is some effort in place to handle non-ASCII paths.  However, on platforms that decline to specify a filesystem encoding (of UTF-8), there are still problems.  Mainly, FilePath naively passes unicode around and when something tries to encode it using ASCII, there can be problems.

For now, testing against non-ASCII paths is disabled.  This is done by having magic_folder.test.strategies.path_segments only build ASCII unicode paths.  It should be possible to have this build non-ASCII unicode paths too and any tests that fail should be fixed.

**Comment by meejah** [comment]
I think https://github.com/LeastAuthority/magic-folder/commit/beb54376cd3c5f780b74f019e13ac620314bd5d8 means this is essentially done (there's a separate ticket about normalization).
