### ISSUE TITLE
`tox -e codechecks` no longer works on main

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/magic-folder#384]
Haven't delved in yet, but `tox -e codechecks` no longer runs for me on current `main`:

```
codechecks run-test-pre: PYTHONHASHSEED='48812982'
codechecks run-test: commands[0] | flake8
ERROR: InvocationError for command could not find executable flake8
```

**Comment by meejah** [comment]
Still not sure what's up exactly .. if I fix the shallow problem of "flake8 not installed in codechecks" then several `flake8` processes consume all my cores for several minutes before I kill them all...

**Comment by meejah** [comment]
I guess a further question / issue is how `flake8` runs in CI if tox wasn't/isn't installing the right stuff...

**Comment by sajith** [comment]
With the `tox.ini` on `main`, I think `flake8` must be running on everything (including things under `venv`) instead of just `flake8 src/magic_folder misc setup.py integration`.

I'm not sure how `flake8` gets installed in tox `codechecks` env without being in the `deps` list.

**Comment by tomprince** [comment]
What happens if you try `tox --recreate -e codechecks` once?

**Comment by meejah** [comment]
Approximately the same, after the re-install: 10+ minutes of pinned cores until I kill things.

**Comment by tomprince** [comment]
Do you have a non-tox venv, or other large directories in your source checkout, or a [user flake8 config](https://flake8.pycqa.org/en/latest/user/configuration.html)?

> I'm not sure how `flake8` gets installed in tox `codechecks` env without being in the `deps` list.

It is installed as a test dep of magic-folder. However, tox doesn't automatically install new dependencies (and it installs the package itself with `--no-deps` by default. So an existing tox virtualenv would not have picked up the new dependency.

**Comment by meejah** [comment]
Yes, I have non-tox venvs.
