### ISSUE TITLE
Uploader race-condition could lose Snapshots

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/magic-folder#385]
`MagicFolderConfig.get_local_snapshot` actually reads all snapshots for that path, and `MagicFolderConfig.delete_localsnapshot` deletes all snapshots for that path. So:

1. read all snapshots
2. write all snapshots that existed at point (1)
3. delete all snapshots that exist at point (3)

If snapshots are created between 1 and 3, they'll get lost. There are a couple of ways to address this:
- change `delete_localsnapshot` to only delete the snapshots passed to it (incidentally, that functions needs to be changed to delete data from related tables, probably)
- change `write_snapshot_to_tahoe` to not be recursive, and upload them one at a time, deleting from the database as we go.
I prefer the second option, even though it may be more work, as it lets us make progress, even if we can't upload all the snapshots at once.

_Originally posted by @tomprince in https://github.com/LeastAuthority/magic-folder/pull/381#discussion_r644421585_

**Comment by meejah** [comment]
Consider the simplest case: a local snapshot with an upstream:

```
Remote A <-- Local B
```

When uploading, we:

1. upload Local B (setting parent to Remote A) yielding "Remote B"
2. add "Remote B" to our Personal DMD
3. set our remotesnapshot table to point at Remote B (instead of Remote A)
4. delete Local B from the database

(We might want to swap 2  and 3 around). If we crash between those steps (whether they're reversed or not) our Personal DMD will be out-of-sync with our local state.

If we crash at any point before 4 we will re-try the whole operation on startup:
- if we'd failed to complete 1 this is fine
- if we'd failed to complete 2 this is fine
- if we'd failed to complete 3 we'd be locally out-of-sync .. but we'd re-sync as the operation is re-tried
- if we'd failed to complete 4 this is fine

So, I think from an upload perspective alone we'll correctly create the right state (eventually) no matter where we crash.

Now, consider if a _new_ LocalSnapshot is created during the operation. With the "load all snapshots, then recurse" (i.e. as implemented now) this snapshot will be lost (because we'll load just ``Local B`` at the start but when we reach step 4, _all_ snapshots for that name are deleted).

So that means: a new ``Local C`` appears in the database, with ``Local B`` as parent. When deleting ``Local B`` we need to adjust ``Local C``'s parent to be ``Remote B`` instead. (With the "one at a time" method we'll need to add this step anyway; every pointer will have to be adjusted as each LocalSnapshot is deleted).

Another alternative would be to lock updates to local snapshots during upload (whether that upload is "all at once" or "one at a time"). This might be conceptually easier to understand. It's probably still better to do "one at a time" anyway so that we preserve our progress (e.g. if we're uploading two snapshots and crash right near the end of the second we'll repeat both uploads).

One reason to do the "all at once" way (that is, adjust the `delete` operation so it keeps any LocalSnapshots for that name created during the upload) is because this would mean fewer updates to the Personal DMD. Not sure that this really matters apart from some minor efficiency (i.e. fewer Tahoe operations), but it would slightly increase the chance of conflicts in multi-user cases.

**Overall we need to emphasize correctness here** and should probably choose the simplest-to-understand implementation -- it should be rare for there ever to be more than a single LocalSnapshot for a given name (unless Tahoe is offline or very slow).

**Comment by tomprince** [comment]
> [...] because this would mean fewer updates to the Personal DMD.

We could avoid this by only updating the DMD at the end, as long as we somehow tracked the remote snapshots created, but this probably doesn't make sense.

>  it should be rare for there ever to be more than a single LocalSnapshot for a given name (unless Tahoe is offline or very slow)

Very slow might just mean that the file is comparatively large. I suspect that it will only be slightly rare.

-----

One thing we should make clear is what the relationship between the machine's DMD and the remote snapshot table is.

**Comment by meejah** [comment]
> We could avoid this by only updating the DMD at the end, as long as we somehow tracked the remote snapshots created, but this probably doesn't make sense.

We do track the (current) remote in the remotesnapshots table; that should be sufficient (we don't need "all" just "the latest"). But it does seem more-correct to update the Personal DMD.

> One thing we should make clear is what the relationship between the machine's DMD and the remote snapshot table is.

I think it's "just" a cache (or at least, could be thought of that way).

IIRC, I believe the main reason it exists is so that we can properly construct LocalSnapshots while offline. Of course, to *upload* those LocalSnapshots, we have to have a Tahoe connection .. so we could instead ensure that the very first Tahoe operation is always "cache the Personal DMD" and thus insert the right parent at upload time.

We could also use it to directly recover from the case where we've uploaded a snapshot (and updated our remotesnapshot table) but before updating the Personal DMD. That is, at startup make sure everything in our remotesnapshot table matches the entries in our Personal DMD (by writing our local entry if they differ). We'll still recover (eventually) when we re-upload the snapshot etc. though so this would just be an optimization (i.e. avoid re-uploading the LocalSnapshot that didn't complete).

**Comment by meejah** [comment]
things are now uploaded one at a time.
