### ISSUE TITLE
Get rid of all non `allmydata.uri` and `allmydata.interfaces` imports of `allmydata`.

### ISSUE THREAD

**Issue by tomprince** [LeastAuthority/magic-folder#391]
The listed imports are for dealing with tahoe URIs, which we want to use as a library. The rest are holdovers from extracting the code base from tahoe.

**Comment by tomprince** [comment]
After #392 and #393, the only remaining non-test imports will be:
- `magic_folder.cli`:
    - `from allmydata.util.encodingutil import argv_to_unicode, to_bytes,`
    - `from allmydata.client import read_config`
- `magic_folder.*.inotify`
    - I suspect these modules can be removed, or they'll be rewritten.

**Comment by meejah** [comment]
Yeah, I'd not worry about the `inotify` modules for now, I think your prediction is accurate.

For the uncode-ish stuff in `cli` probably best to wait until we actually support Python3? I'd personally rather use `Click` for the CLI -- but also lets not do anything there until "release 2" or beyond.

For `read_config` it seems that's only for figuring out "shares needed" .. that's probably best gotten from some (maybe new) Tahoe API anyway. Perhaps there's already a non-config way to get it. But probably that can wait too?

(My assumption here is that we're still planning on a Python2 first release so depending on things from Tahoe is still fine short-term).

**Comment by meejah** [comment]
Hmm, further to the `read_config` thing: that is really kind of a holdover, we could probably just remove the "ready enough" code since we do handle when Tahoe is offline -- and we have to handle that anyway, because our Tahoe client could fail to upload for many reasons besides "not connected to enough storage servers"...I filed https://github.com/LeastAuthority/magic-folder/issues/397 to discuss that aspect.

**Comment by meejah** [comment]
I don't know that I wrote this down anywhere, but my thought is that if we can concentrate all our use of `allmydata.*` into `magic_folder.util.capabilities` that would be great. That is, all magic-folder code that needs to manipulate capabilities uses methods from there.

(At that point, we could decide to just copy in the hopefully-small amount of required Tahoe code if we wanted to eliminate the direct tahoe dependency at any moment).
