### ISSUE TITLE
Evaluate whether we should store the collective DMD of a folder as part of the personal DMD.

### ISSUE THREAD

**Issue by tomprince** [LeastAuthority/magic-folder#396]
From [Leif's proposal](https://magic-folder.readthedocs.io/en/latest/proposed/magic-folder/multi-party-conflict-detection.html#overview):
> Inside the dmd there will also be an immutable directory containing the client’s subscriptions (read-caps to other clients’ dmds).

That suggest that we should be storing the collective DMD as a entry (we can use the namespace that #395 mentions) in the personal DMD. This gives a fairly straightforward way to add new participants from any machine, if each machine maintained its own collective DMD, and merged entries from other DMD it looks at.

There definitely needs to be some thought on when we should add new machines that we discover, and how we might handle deletion of a machine ([this](https://tahoe-lafs.readthedocs.io/en/latest/specifications/dirnodes.html#revocation) suggests we'd need to create a new personal DMD, and share it with all the machines that aren't being removed.

**Comment by tomprince** [comment]
(Note that unless we store subscriptions opaquely, we can't use an immutable directory, since tahoe enforces deep immutability.)

**Comment by meejah** [comment]
We've discussed various ways to communicate the participants in a Folder.

The current implemented way (a single Collective DMD) is closer to the old-magic-folders and easier to understand than more complex arrangements.

Another method is to not have any Collective DMDs at all and communicate only during the "invite" phase. This method lacks a way to communicate _updates_ to the participant list, however -- you'd need to do an "invite" from each participant to each other one.

The different ways of communicating "who are the participants" also have different use-cases. Allowing any participant to add others supports different use-cases than a single "admin" device. (For example, some groups do prefer admins to control access).

With "one Collective per device" we also would need to consider "non-mutual" arrangements if participants can choose who to accept in to their own Collective DMDs (e.g. if Alice pulls updates from Carol but Carol does not also pull updates from Alice).

**Comment by tomprince** [comment]
> (For example, some groups do prefer admins to control access)

Sure, though admin and admin-device are separate concepts, I suspect there is a certain extent to which people want to limit access to the former as opposed to the later.

One thing to keep in mind is the nature of tahoe prevents tight control by an admin about what access is shared by other people with access to dircaps. I think it might be reasonable to acknowledge that in our design, and not pretend to allow limiting access to admins.

> With "one Collective per device" we also would need to consider "non-mutual" arrangements if participants can choose who to accept in to their own Collective DMDs (e.g. if Alice pulls updates from Carol but Carol does not also pull updates from Alice).

My impression of our anticipated recovery flow (from previous conversations) is exactly this, so I think we'll need to deal with this case in our initial implementation.

> The different ways of communicating "who are the participants" also have different use-cases. Allowing any participant to add others supports different use-cases than a single "admin" device. (For example, some groups do prefer admins to control access).

The different use cases could be reflected in how we store the participants, or how we reconcile differences in them.

**Comment by meejah** [comment]
> One thing to keep in mind is the nature of tahoe prevents tight control by an admin about what access is shared by other people with access to dircaps. I think it might be reasonable to acknowledge that in our design, and not pretend to allow limiting access to admins.

We are limiting access to admins-only. The admin is the sole device with the write-cap to the Collective.

**Comment by meejah** [comment]
> My impression of our anticipated recovery flow (from previous conversations) is exactly this, so I think we'll need to deal with this case in our initial implementation.

We're talking about different things, then, perhaps: with the current design, there is only one place to find "the participants in a Folder" and that is from the Collective DMD. So, there is no confusion.

If each device decided its own participant list, then the question arises: does carol believe the participants are "alice + carol", or just "carol". This is the issue I was getting at originally up there.

We do not need to entertain additional Participants designs for any immediate needs.

**Comment by tomprince** [comment]
> > My impression of our anticipated recovery flow (from previous conversations) is exactly this, so I think we'll need to deal with this case in our initial implementation.
> 
> We're talking about different things, then, perhaps: with the current design, there is only one place to find "the participants in a Folder" and that is from the Collective DMD. So, there is no confusion.
> 
> If each device decided its own participant list, then the question arises: does carol believe the participants are "alice + carol", or just "carol". This is the issue I was getting at originally up there.
> 
> We do not need to entertain additional Participants designs for any immediate needs.

https://privatestorage.slack.com/archives/CGU11ERUG/p1622739174285400 describes the flow for recovery as adding the old device's personal DMD as a participant in the new device's personal DMD.

> > One thing to keep in mind is the nature of tahoe prevents tight control by an admin about what access is shared by other people with access to dircaps. I think it might be reasonable to acknowledge that in our design, and not pretend to allow limiting access to admins.
> 
> We are limiting access to admins-only. The admin is the sole device with the write-cap to the Collective.

Any user with access to the folder could setup their own collective DMD with whoever they want in it, and then data would sync from whoever they added to the user to the admin.

**Comment by tomprince** [comment]
> > We are limiting access to admins-only. The admin is the sole device with the write-cap to the Collective.
> 
> Any user with access to the folder could setup their own collective DMD with whoever they want in it, and then data would sync from whoever they added to the user to the admin.

The point being, the limitations we impose with client side code are not things that we can enforce. Given the lack of notion of identity and tracking that are inherent in our product, we need to be careful about the limits of what we can guarantee about how data will be accessed.

When using something like google drive or dropbox, and admin can limit who can access the service and enforce things like 2FA and have access to audit logs for things like IP addresses of the people who access resources.

By design we *can't*. While that is a feature, I think we need to be careful about suggesting to users that they can enforce the same kind of limitations about sharing that they can with other services that have identity.

**Comment by meejah** [comment]
> https://privatestorage.slack.com/archives/CGU11ERUG/p1622739174285400 describes the flow for recovery as adding the old device's personal DMD as a participant in the new device's personal DMD.

...as a participant in the new device's _Collective_ DMD. So the new device is admin on the new folder which will have two participants: the new device and the old device.

(The old folder continues to have one participant: the old device).

**Comment by meejah** [comment]
> Any user with access to the folder could setup their own collective DMD with whoever they want in it, and then data would sync from whoever they added to the user to the admin.

Sure, and even without that, anyone could just copy files they sync'd onto Dropbox or whatever.

**Comment by tomprince** [comment]
> > https://privatestorage.slack.com/archives/CGU11ERUG/p1622739174285400 describes the flow for recovery as adding the old device's personal DMD as a participant in the new device's personal DMD.
> 
> ...as a participant in the new device's _Collective_ DMD. So the new device is admin on the new folder which will have two participants: the new device and the old device.
> 
> (The old folder continues to have one participant: the old device).

Yes, exactly. That is exactly what you described in https://github.com/LeastAuthority/magic-folder/issues/396#issuecomment-855595019
> With "one Collective per device" we also would need to consider "non-mutual" arrangements if participants can choose who to accept in to their own Collective DMDs (e.g. if Alice pulls updates from Carol but Carol does not also pull updates from Alice).

**Comment by meejah** [comment]
So, logically after a recovery there are now two Magic Folders: the old one (1 participant) and the new one (2 participants). They each have an unambiguous way to determine who the participants are: check the Collective for each.

**Comment by tomprince** [comment]
> So, logically after a recovery there are now two Magic Folders: the old one (1 participant) and the new one (2 participants). They each have an unambiguous way to determine who the participants are: check the Collective for each.

It isn't clear to me why this is preferable to having per-device collectives. As described, we have exactly the same datastructures, we are just labelling the bits of them differently[1].

In particular, I think having a single on-disk folder being a participant in multiple magic-folders seems like a weird thing to explain to users. (This also suggests that we should have a better word than "participant" for this concept)

[1] Certainly the labelling impacts what operations we expose, but it isn't clear to why multiple magic-folders with partly overlapping participants is the model we want to expose.

**Comment by meejah** [comment]
> It isn't clear to me why this is preferable to having per-device collectives.

We already have it. This is the method of participant-specification we agreed to pursue first in  the OTF design. We can add others later, if required.

**Comment by tomprince** [comment]
> > It isn't clear to me why this is preferable to having per-device collectives.
> 
> We already have it.

That would be a reason that why (if we decide we want to have a per-device collective DMD), we choose not to implement that change in time for v1. That **is not** a reason why it is preferable long-term.

> This is the method of participant-specification we agreed to pursue first in the OTF design. We can add others later, if required.

Is there documentation on why the OTF design decided to diverge from the Leif model on this point? I find it hard to reason about designs that I think are plausibly incorrect without any record about how that design came to be or what alternatives were considered. Particularly when the context has changed since those decisions were made.

**Comment by meejah** [comment]
I don't know if there is such documentation. It is very close to the old magic-folder method is, IIRC, the reason.

Before implementing a "more distributed" way of communicating participants, it was desirable to keep the well-used, familiar and simpler design of a single source of truth.

**Comment by tomprince** [comment]
> Before implementing a "more distributed" way of communicating participants, it was desirable to keep the well-used, familiar and simpler design of a single source of truth.

It isn't clear to me that it **is* simpler. Particularly in light of the fact that it adds the complication of https://github.com/LeastAuthority/magic-folder/issues/396#issuecomment-860944403.

For what we are implementing for v1 at least, we could treat the local device's collective DMD as the single source of truth, and not look at those of any other participant. That is essentially what we are doing now in the recovery flow, except we currently treat them as being distinct folders, rather than different views on who the participants in the same folder.

**Comment by meejah** [comment]
A different method of organizing participation needs users-stories and other design, and it's not as simple as this ticket implies. (Such other designs can be found in the OTF documents).
