### ISSUE TITLE
Figure out how to easily track python requirements in nix.

### ISSUE THREAD

**Issue by tomprince** [LeastAuthority/magic-folder#409]
We should file a bug to upgrade it then .. and/or figure out some wider strategy about how to ensure Nix can track our Python requirements since I suspect this will be the case (i.e. "Nix has old version") for almost anything we want to upgrade..?

_Originally posted by @meejah in https://github.com/LeastAuthority/magic-folder/pull/405#discussion_r649366958_

**Comment by meejah** [comment]
No longer relevant in this project
