### ISSUE TITLE
Pin all of our requirements, and automate updating them to new versions.

### ISSUE THREAD

**Issue by tomprince** [LeastAuthority/magic-folder#410]
Since we are planning to distribute this as a bundled application, we should pin all of our dependencies exactly, so that we are testing exactly what we ship to users.

We should additionally automate updating those dependencies, using something like [dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates)

**Comment by meejah** [comment]
We should also bear in mind that the bundle is a PyInstaller bundle so we should do whatever is best for that target (cc @crwood if there's anything to keep in mind here?)

**Comment by tomprince** [comment]
It looks like gridsync uses this for the other commands it bundles (see https://github.com/gridsync/gridsync/tree/master/requirements), but not yet magic-folder.

If we were to include a `requirements.txt` in our repo, gridsync could just directly consume that.

**Comment by tomprince** [comment]
It looks like dependabot doesn't support python 2.7 anymore, so we won't have automatic updates until we switch to python 3.
