### ISSUE TITLE
Handle adding support for local snapshots to point at remote snapshots.

### ISSUE THREAD

**Issue by tomprince** [LeastAuthority/magic-folder#426]
https://github.com/LeastAuthority/magic-folder/blob/2241da7891756f806be3c02f81a8273450560a4b/src/magic_folder/uploader.py#L117-L121

**Comment by meejah** [comment]
This is in https://github.com/LeastAuthority/magic-folder/pull/381

**Comment by meejah** [comment]
Since #381 is in this is done, AFAIK
