### ISSUE TITLE
Magic-folder will overwrite files that are changed while it is trying to write a new remote version.

### ISSUE THREAD

**Issue by tomprince** [LeastAuthority/magic-folder#456]
When magic-folder has decided to overwrite a file with a remote version, there is a window where it may lose a local change, if it races another program trying to write the file.

This is related to #455, but harder to address. Even if we check that there aren't local changes when we decide to overwrite, there is an unavoidable window between when we check and when we write the file,

There is a proposal (#454) for how to notice when we encounter that race condition, in a way that we don't lose any changes.

**Comment by meejah** [comment]
both referenced tickets have been implemented.
