### ISSUE TITLE
Stop using mangled paths, except for tahoe directory entries.

### ISSUE THREAD

**Issue by tomprince** [LeastAuthority/magic-folder#499]
The reason we use mangled paths, is because we want to use a flat directory structure for a magic-folder. The only place that cares about having a `/` in the name is the directory entry, so we should confine the mangling of names to there, rather than also keeping them mangled in the database or in the snapshot metadata.

This simplifies a lot of code, and also limits the number of places that #395 needs to be dealt with.

**Comment by meejah** [comment]
I don't understand the motivation here. "The name" of a snapshot is the thing that's in the DMD and so it makes sense to have that name match in the database.

**Comment by tomprince** [comment]
As a practical matter, before the attached patch, there are 11 places where we need to demangle the name, and 2 where we need to mangle it (outside of tests); after the patch there is one place each where we mangle or demangle the name. That suggests to me that the natural form to store the name is the unmangled name.

The mangled name is an implementation detail of how we have a flat tahoe directory, due to details of tahoe's HTTP API[1]. We don't ever want to show a mangled name to the user, and generally don't want to use mangled names when writing or reading files to disk[2]. Given that there are quite a few places where we want to display things to the user or interact with the filesystem, but only one place where we read, and two places (one after the linked PR) where we need to interact with tahoe, I think it makes more sense to use the unmangled named everywhere we can.

Another point, is that unmangled named is fixed[3], but the mangled named name isn't (i.e. we are free to choose a different encoding in the future). Given that, I think it makes more sense to choose the more stable format (even if it is unlikely that we will change the mangling). This is *particularly* true of the name we store in the snapshot metadata, as we can't upgrade that in the future (of course we could always bump the metadata version, and de-mangle the name when reading the old version, but it seems easier to just side-step the issue entirely).

[1] I don't actually think that tahoe enforces that `/` isn't in a directory entry name, it just doesn't provide a way to write a single entry with one, if we used `set-children` to update the DMD, we could probably use `/`. I think this probably isn't a good idea though.
[2] I could see wanting to use some form of mangled name for stash files.
[3] ignoring possibly `/` vs `\` issues.

**Comment by meejah** [comment]
> As a practical matter, before the attached patch, there are 11 places where we need to demangle the name, and 2 where we need to mangle it (outside of tests);

Make a `.relpath` property on the Snapshot instead?
Regardless, that doesn't explain what the motivation is to de-couple a Snapshot from its name by splitting all the args.

If you think "a Snapshot's name" should be a tuple of path-segments or whatever then produce a proposal for that. This seems to confuse the matter even further to me.

> we are free to choose a different encoding in the future

Not without upgrading the version, surely. The "mangled name" is just as fixed as anything else.

**Comment by tomprince** [comment]
>> As a practical matter, before the attached patch, there are 11 places where we need to demangle the name, and 2 where we need to mangle it (outside of tests);
> 
> Make a `.relpath` property on the Snapshot instead?

What benefit do we gain by using the mangled name *anywhere* other than right at the edge when we are writing to or reading from a DMD?  I really struggle to see any practical or conceptual benefit by using the mangled name, rather than just the name, anywhere we don't absolutely have to.

In any case, we case, we don't always have an object we can put that on. For example, if we want to have a 
`/magic-folder/<folder_name>/file-status/<file-name>`, without this patch, we would need another call to `path2magic`; with it, we won't need one. Basically the only point we will need to care about the mangled name is when dealing with a DMD, which this patch isolates to `magic_folder.participants`. That is the point of having abstractions, to avoid needing code everywhere needing to worry about details of how we store snapshots in DMDs.

> Regardless, that doesn't explain what the motivation is to de-couple a Snapshot from its name by splitting all the args.

That is a separate issue with different reasoning for the change, that just happens to be changing the same code, and are adjacent in that they are both about how and where we get the name[1].

The main reason is because we can't and don't access a snapshot by the name stored in its metadata, so we should use the same name we *do* access it by, whenever we needs its name. This is essentially the same reason why use normalized database tables, to avoid duplication, and to prevent errors when to pieces of data that should be the same get out of sync.

(I'd be happy to get rid of the metadata name entirely, but I'm not arguing that here)

> If you think "a Snapshot's name" should be a tuple of path-segments or whatever then produce a proposal for that. This seems 
to confuse the matter even further to me.

I am proposing here that a snapshots name should be a `/` separated string of path segments (which is already how we name them for users and in the API).

> > we are free to choose a different encoding in the future
> 
> Not without upgrading the version, surely. The "mangled name" is just as fixed as anything else.

My point is that there is not a meaningfully different representation of an unmangled path (at least as a string), so even if we bump the version, we can't meaningfully change it. In that sense, it is more fixed than the mangled name.

----

[1] Also, given that I have PRs that have been waiting for review for most of a month, I have some reluctance to disentangle things as a separate PRs.

**Comment by meejah** [comment]
If you want it to be true that "a snapshot's name is the relpath" then why add `relpath` as an arg to all the APIs? (And why call it "name" at all then?)

**Comment by tomprince** [comment]
> If you want it to be true that "a snapshot's name is the relpath" then why add `relpath` as an arg to all the APIs?

Because (as has been discussed extensively in response to https://github.com/LeastAuthority/magic-folder/pull/500#discussion_r672582638; I'm not going to reiterate all the arguments here), the source of truth (IMO) for that value isn't available as part of `RemoteSnapshot`, so we either need to pass another argument, or add a new abstraction.

>(And why call it "name" at all then?)

I'd happily not call it name at all. I'd happily follow this up with an issue/PR to remove any references to a snapshot's name, and only refer to it as a relpath.
