### ISSUE TITLE
The Nix packaged magic-folder does not build properly except from a git checkout because it has no `_version.py`

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#526]
`setup.py` does some tricky things with `git` to automatically determine a version and then write it to `_version.py` for subsequent use after the git state is no longer available.

If `setup.py update_version` is run and the working tree is not a git checkout (or whatever you call a directory with a `.git` containing the usual stuff) then it silently does nothing.  Subsequently, `magic_folder/__init__.py` is broken because it cannot import `magic_folder._version`.

In most usage so far, the in-repo Nix packaging does not trip over this because it declares the magic-folder source to be the working tree itself and that working tree is almost always a git checkout (eg on CI, in a developer's working environment, etc).

However, any source tarball is generally missing `.git` and its contents.  This applies to a very common out-of-tree Nix invocation which uses the GitHub "archive" feature to get a source tarball without `.git`.  Consequently, in this usage, there is no `_version.py` and the build fails.

This blocks efforts to integrate stand-alone magic-folder with GridSync on NixOS which effectively means it blocks running GridSync w/ stand-alone magic-folder on NixOS entirely since the AppImage distribution does not work on NixOS (I don't understand why) and a pip-based installation involves building most of Qt which takes many hours, even ignoring the tedious process of setting up and maintaining the build environment.

**Comment by exarkun** [comment]
Oh, and for extra sneakiness, if `setup.py update_version` has ever succeeded in a particular working tree then `_version.py` has been written and if it is not cleaned up then it will serve to obscure this problem in that particular working tree until it is removed.

**Comment by meejah** [comment]
Is this leftover "versioneer" stuff?

**Comment by meejah** [comment]
Anyway, since there are no releases yet and AFAIK no "how to do a release" then I suppose we could write one, and it could include a way to update the version without using "versioneer" (or wherever that stuff came from before tahoe).

**Comment by exarkun** [comment]
> Is this leftover "versioneer" stuff?

I don't think it was ever versioneer.  It is some kind of weird version-y stuff that was inherited from Tahoe-LAFS, though (maybe it is the predecessor to versioneer or something).

> Anyway, since there are no releases yet and AFAIK no "how to do a release" then I suppose we could write one, and it could include a way to update the version without using "versioneer" (or wherever that stuff came from before tahoe).

That's fine with me.  That seems like a follow-up ticket?

**Comment by meejah** [comment]
Sure, yeah, followup is fine .. I just mean that we could delete _all_ this "code that determines versions" stuff and choose to burn in the version somewhere (I think last I tried the least number of spots I got to was "two" .. that might have been "once in the code, once in git"). To be concrete I mean just literally putting `version = "2021.0.0"` in e.g. `_version.py` or whatever.

Obviously, _ideally_ there'd be a single spot .. but pragmatically, as long as the "how to do a release" document tells someone where to bump versions having two spots isn't terrible. And I think that's _less terrible_ than having a bunch of weird git/import/.py-parsing code instead.

**Comment by exarkun** [comment]
Elsewhere, the direction seems to be more _towards_ deriving version information from git.  Versioneer is one example but from discussion I've seen in Twisted channel, there's at least one other system where git tags are used to determine a version.

I don't have a strong position on this, except maybe to point out that I don't really know how the Python world is approaching this problem these days, and maybe it's worth looking around to see if there are other good options we're not aware of.

**Comment by exarkun** [comment]
> Sure, yeah, followup is fine .. I just mean that we could delete all this "code that determines versions" stuff and choose to burn in the version somewhere (I think last I tried the least number of spots I got to was "two" .. that might have been "once in the code, once in git"). To be concrete I mean just literally putting version = "2021.0.0" in e.g. _version.py or whatever.

Okay.  The easiest path forward seemed to just be to jump in on this idea.  The linked PR now deletes all of that auto-versioning code and burns the version in to a few places.  I also added the *start* of a release doc that just mentions these three places so at least this change isn't increasing the amount of _undocumented_ release-related complexity.

**Comment by meejah** [comment]
Cool .. BTW I filed https://github.com/LeastAuthority/magic-folder/issues/532 for the "make an actual plan" part...
