### ISSUE TITLE
Magic-Folder immediately terminates after starting with "Error: upload_queued() takes exactly 3 arguments (4 given)"

### ISSUE THREAD

**Issue by crwood** [LeastAuthority/magic-folder#530]
I'm not sure exactly _how_ this happened but I seem to have gotten Magic-Folder (version 0.0.0.post2293) into a state that causes it to shut down immediately after starting up (due, apparently, to the `upload_queued` function being passed too many arguments). My stdout/stderr is as follows:

```
[magic-folder:stdout] 2021-08-02T16:34:35-0400 Polling connected enough...
[magic-folder:stdout] 2021-08-02T16:34:35-0400 connected enough: Found 1 of 1 connected servers (want 1), done.
[magic-folder:stdout] 2021-08-02T16:34:35-0400 Site starting on 46703
[magic-folder:stderr] Error: upload_queued() takes exactly 3 arguments (4 given)
[magic-folder:stderr] 
[magic-folder:stdout] 2021-08-02T16:34:35-0400 (TCP Port 46703 Closed)
[magic-folder:stdout] 2021-08-02T16:34:35-0400 Main loop terminated.
```

And the (especially short) eliot log: 

```
{"action_status": "started", "action_type": "downloader:scan-collective", "folder": "Cat Pics", "task_level": [1], "task_uuid": "54ede699-98b5-4ab6-8719-8e6cc758236c", "timestamp": 1627936475.74064}
{"action_status": "started", "action_type": "magic-folder:cli:list-dir", "api_uri": "http://127.0.0.1:39849/uri/URI%3ADIR2%3Aey2nqfuex3wa5jtwel3ixsz6ie%3Ay76a7sdtbcx5g6gfwaci33agu7qftv7kdltr2levl3te3ltetnea?t=json", "dirnode_uri": "URI:DIR2:ey2nqfuex3wa5jtwel3ixsz6ie:y76a7sdtbcx5g6gfwaci33agu7qftv7kdltr2levl3te3ltetnea", "task_level": [2, 1], "task_uuid": "54ede699-98b5-4ab6-8719-8e6cc758236c", "timestamp": 1627936475.741391}
```

As far as I can tell, once the application in this state, the error will recur with every subsequent launch of the Magic-Folder daemon and thus appears to be unrecoverable; a user who faces it will presumably be unable to use Magic-Folder.

**Comment by crwood** [comment]
After further investigation, it looks like this behavior/state can be reproduced simply by terminating the magic-folder process while at least one upload is queued/in-progress (e.g., by `touch`ing some number of files in a magic-folder directory and killing the application shortly afterward).

**Comment by tomprince** [comment]
Do you have the git commit of the code you are running? I'm guessing it is missing https://github.com/LeastAuthority/magic-folder/pull/525/commits/953da898b759291f874f56a68923b820d7412004 from #525.

**Comment by crwood** [comment]
Ah, yes! I was on -- 443e46bb687669778c66fb4cf4edf512a9a343df -- the commit immediately before 953da89...

Pulling in 953da89 fixes it. Thank you! :)
