### ISSUE TITLE
Windows-specific "colorama" transitive dependency is undeclared

### ISSUE THREAD

**Issue by crwood** [LeastAuthority/magic-folder#555]
When attempting to install/build Magic-Folder on Windows via `python -m pip install  --require-hashes -r requirements\base.txt` and `python -m pip install --no-deps .` I observe the following error:

```
Collecting colorama; platform_system == "Windows"
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    colorama; platform_system == "Windows" from https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl#sha256=9f47eda37229f68eee03b24b9748937c7dc3868f906e8ba69fbcbdd3bc5dc3e2 (from tqdm==4.61.2->-r requirements\base.txt (line 372))
```

I'm happy to submit a PR to add this, but I've never used `pip-compile` and am unsure what the preferred workflow/process is for this project (e.g., `requirements/base.in` or `requirements/plateform.txt`).

**Comment by meejah** [comment]
I don't know how that stuff works either; what I _do_ know is in the README in the directory there.
