### ISSUE TITLE
Leaving folders that are actively synchronizing becomes impossible

### ISSUE THREAD

**Issue by crwood** [LeastAuthority/magic-folder#587]
In the Gridsync integration test suite, I have a simple helper/teardown function that some tests use to leave all magic-folders for a given Magic-Folder instance, like so:

```
@inlineCallbacks
def leave_all_folders(magic_folder):
    folders = yield magic_folder.get_folders()
    for folder in list(folders):
        yield magic_folder.leave_folder(folder)
```

(where `leave_folder` sends an authenticated `DELETE /v1/magic-folder/<folder>` request)

Up until recently, this has worked fine: I could create/join numerous (~10) magic-folders and use the function above to leave them all in quick succession without problems. As of the current Magic-Folder main@HEAD (revision 8e44c20c8695069522abb34cd594875dd80b59dd), however, this function causes Magic-Folder to hang: typically the first three or four folders will leave successfully (as indicated by receiving a response body of `{}`), but the next subsequent request will hang and never return anything.

If I introduce a slight pause in between requests like so, however, the requests complete successfully:

```
@inlineCallbacks
def leave_all_folders(magic_folder):
    folders = yield magic_folder.get_folders()
    for folder in list(folders):
        yield deferLater(reactor, 0.1, lambda: None)
        yield magic_folder.leave_folder(folder)
```

Given this, I suspect that there's some deeper problem here with rapid configuration updates (maybe related to the `DeferredLock` that was introduced in #583?), and that this problem was introduced somewhere between revision ed4af492cf8ce3a76c48d429a44a510ba17ea816 and revision 8e44c20c8695069522abb34cd594875dd80b59dd (since if I roll back to ed4af492cf8ce3a76c48d429a44a510ba17ea816 I can leave all folders in quick succession without the hang).

I will try to get some logs shortly...

**Comment by meejah** [comment]
I believe I've repeated this with a "largely automated" test; the folders being left must be "doing stuff" (that is, sync-ing) for this to manifest.

So I believe this is likely related to the generally more-robust retry behavior: the "syncing" folder is trying to update the database but the database is gone, so it retries later. (e.g. if you're seeing the same failure I am, there will be a bunch of public "Error updating personal DMD: Tried to operate on a closed database  ..." errors in the status).

I'm going to change the title to reflect this...

**Comment by meejah** [comment]
I'm not yet sure why this causes the "leave" Web requests to be held open indefinitely though..

**Comment by crwood** [comment]
Glad you were able to reproduce this. It seems highly plausible to me that the behavior is indeed triggered for folders that are still actively syncing (as I wasn't able to reproduce it with an isolated test that simply adds 100 folders then calls `leave_all_folders`).

If it's at all useful to you, [here](https://github.com/LeastAuthority/magic-folder/files/7477418/magic-folder-eliot.log) is an eliot log from a Gridsync test run that triggers the behavior. I see some dangling `TahoeAPIError`s in there but I don't know enough about eliot to figure out whether those are related to this issue -- or even what they're related to more generally.

**Comment by crwood** [comment]
It looks like rev 9d21ecaad29d61d47b836402f2239b762f702f64 is the specific commit that introduces the hold-requests-open-indefinitely behavior; I'm unable to reproduce it prior to then.

**Comment by crwood** [comment]
Further debugging (using the `meejah:587.cancel-behavior` branch at rev `535b862`) indicates that the folder which hangs is (always?) one for which a `scan-local` was very recently requested: if I (1) write a couple of files, (2) request a `PUT /v1/magic-folder/{folder_name}/scan-local`, and then immediately (3) request a `DELETE /v1/magic-folder/{folder_name}`, the request hangs forever and I never get a response, _but_ if I (1) write a couple of files, (2) request a `PUT /v1/magic-folder/{folder_name}/scan-local`, _(3) wait for 0.5 seconds_, and then (4) request a `DELETE /v1/magic-folder/{folder_name}`, the operation completes successfully.

I'm guessing there's some post-scan operation here (an upload? A remote snapshot write?) that's preventing the `DELETE` from completing.
