### ISSUE TITLE
Re-arrange the repository to make more sense as a stand-alone

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#6]
The repository structure continues to reflect the structure of the magic-folders implementation as it existed inside Tahoe-LAFS.  Without all of the rest of Tahoe-LAFS around it, this structure makes less sense.  Consolidate it somewhat, removing redundancies that exist in the path hierarchies and the extremely sparse directories which now contain only one or two files.

Files / modules which could use a better name (suggested "better name" too, but maybe there's even-better names):

 - [x] `magic_folder/scripts/magic_folder_cli.py` -> `magic_folder/cli.py` (https://github.com/LeastAuthority/magic-folder/pull/49)
 - [x] `magic_folder/frontends/magic_folder.py` -> `magic_folder/magic_folder.py` (https://github.com/LeastAuthority/magic-folder/pull/70)
 - [x] `magic_folder/web/magic_folder.py` -> .`magic_folder/web.py` (https://github.com/LeastAuthority/magic-folder/pull/69)
 - [ ] others?

**Comment by tomprince** [comment]
Anything left to do here?

**Comment by meejah** [comment]
Would be nice to have only one `test_magic_folder.py` and to flatten the `docs` stuff more, but also that's just "nice to have" and we could file different tickets later (so i'll just close this)
