### ISSUE TITLE
prevent starting a second magic-folder 

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/magic-folder#644]
If a magic-folder is running for a particular config-directory, a second one should refuse to start and issue an informative message

**Comment by meejah** [comment]
hmm, I just ran `pip freeze` and it showed up .. I will try in a fresher virtualenv

**Comment by meejah** [comment]
...that said, are "pidfiles" still state-of-the-art for ensuring a single daemon/process is running?

**Comment by meejah** [comment]
I guess the question is: does depending directly on `psutil` have any drawbacks?

**Comment by exarkun** [comment]
They have the problem that pids are not guaranteed unique across time.  A process might be assigned pid X, exit, and then another process is assigned pid X.  If the check is "does a process with pid X exist?" then you get false positives sometimes.  I think this was more common when Linux had sequential pid allocation which maybe it no longer does, but it's still possible.

I don't remember all of the details on Windows.  I think that I do remember that Windows doesn't _really_ have pids, it has something else and then people put a vaguely POSIX-y facade over it (which has created hard-to-understand behavior for other systems, but I dunno how well it works in this case).

On POSIX, a different trick is to listen on a unix socket.  If the process exits, it becomes impossible to connect to the socket.  I don't know of a parallel for Windows, but I would really expect that Windows has some other native mechanism that works reliably.

For some reason, `twisted.python.lockfile` still uses symlinks and pids instead of unix sockets.  I'm not sure why.  Could be there's some extra tricky bits for unix sockets or maybe just lack of maintenance.

**Comment by crwood** [comment]
I don't know about "state-of-the-art" but if you need enforce a process singleton in a cross-platform way (i.e., in a way that works on Windows and that doesn't depend on unix sockets, etc.) it seems like you're going to have to depend on the filesystem (but, on Windows, even that isn't particularly reliable). A lockfile could be another approach.

**Comment by crwood** [comment]
Hah! Sniped by @exarkun. :)

**Comment by crwood** [comment]
>For some reason, twisted.python.lockfile still uses symlinks and pids instead of unix sockets. I'm not sure why.

Because symlink creation is atomic.

**Comment by crwood** [comment]
>They have the problem that pids are not guaranteed unique across time. A process might be assigned pid X, exit, and then another process is assigned pid X. If the check is "does a process with pid X exist?" then you get false positives sometimes.

With `psutil` you could at least look up/verify the name of the process and, e.g., ensure that it's actually a "magic-folder" process before killing.

**Comment by meejah** [comment]
I am aware of the "false positive" possibility.

Some things examine e.g. the command-lines of running processes (but this _also_ has problems, like "maybe it was run in a different manner") so I feel like the safety of not having duplicate processes is outweighed by the (slim?) chance of colliding PIDs on re-start?

**Comment by meejah** [comment]
> With psutil you could at least look up/verify the name of the process and, e.g., ensure that it's actually a "magic-folder" process before killing.

Yes, we could look up details about the process .. but I wasn't planning on killing anything. Instead, the new process will refuse to start (with an informative message). Then, it would be up to the user to take action (e.g. kill that process, or delete the pidfile).
The `psutil` lookup instead is to detect a "stale" pidfile -- e.g. it will delete the `pidfile` if there is no process at all with that PID.

**Comment by exarkun** [comment]
> Some things examine e.g. the command-lines of running processes (but this also has problems, like "maybe it was run in a different manner") so I feel like the safety of not having duplicate processes is outweighed by the (slim?) chance of colliding PIDs on re-start?

I think the question is - what recourse does the user have in this situation?  Presumably they mostly won't know how to get the system to recover, even if magic-folder can successfully communicate the situation to GridSync so it can communicate the situation to the user.

**Comment by meejah** [comment]
> I think the question is - what recourse does the user have in this situation? 

Kill the offending process, or delete the PID file.

**Comment by meejah** [comment]
The default should probably be whichever  one is "expected" on linux-y OSes? but, I don't really know which one that is: kill the process that's "in the way" or exit without doing anything?

(Intuitively to me, the "exit without doing anything" option seems safest: even if we're correct that the offending process _is_ another magic-folder it may be "doing stuff" like uploading a file etc...and if we're wrong we'll kill some "innocent" process).

Whichever is chosen, the "other" behavior could be an option? Or e.g. if magic-folder is being controlled by Gridsync, it could choose to just kill whatever is in the pidfile.

**Comment by crwood** [comment]
FWIW, Tahoe-LAFS just kills whatever pid is in the `twistd.pid` pidfile if that pidfile exists at startup (or at least it _used to_ -- maybe it doesn't anymore now that `tahoe start` and `tahoe stop` were removed?). Buildbot-runners also take the same approach.

**Comment by exarkun** [comment]
I think it would be bad if starting GridSync could sometimes automatically cause one (or N, I guess) of the user's other processes, chosen more or less at random, to be killed.

I think it would only be slightly less bad if this could happen, but not automatically, only after making the user click through a "are you sure you want to do this dangerous thing" dialog.

Maybe one or the other of those is okay as an intermediate step (ie, for this ticket) but I think that ultimately false positive matches should be eliminated so this case doesn't arise at all.

**Comment by meejah** [comment]
Okay, that's probably good for a default here too then.

Since we basically need `psutil` anyway, magic-folders might as well _also_ take some steps to ensure that the process _is_ a magic-folders process (right?).

A

**Comment by meejah** [comment]
> "are you sure you want to do this dangerous thing"

I don't think that's any better than leaving the user to fiddle with the process-manager? (That is, how is a naive user supposed to answer that question?)

**Comment by exarkun** [comment]
> 

> > "are you sure you want to do this dangerous thing"

> I don't think that's any better than leaving the user to fiddle with the process-manager? (That is, how is a naive user supposed to answer that question?)

Yes, I think those are both bad - because a naive user won't answer the question, they'll just click whichever button lets them get on with their life (and maybe suffer the consequences of it being the wrong action).

**Comment by meejah** [comment]
Okay, so the conclusion is: kill the thing in pidfile, but only if we see "magic-folder" somewhere in the command-line of the running process? (Otherwise, tell the user there's a process in the way and refuse to start).

**Comment by meejah** [comment]
...or is that "otherwise just delete the pidfile and run anyway"?

(If there's a pidfile and no running process for that pid, we delete the pidfile and start up anyway).

**Comment by exarkun** [comment]
Does the more-user-facing coordinating layer have to do its own management as well?

If the user launches GridSync, which launches magic-folder, and then the user launches GridSync, does magic-folder expect that GridSync will notice and not try to launch magic-folder again?

If GridSync lets itself run twice then magic-folder noticing that magic-folder already holds the lock and killing it will just lead to a loop where GridSync constantly restarts whichever magic-folder was killed most recently, causing the other to be killed.

**Comment by meejah** [comment]
> If the user launches GridSync, which launches magic-folder, and then the user launches GridSync, does magic-folder expect that GridSync will notice and not try to launch magic-folder again?

No, magic-folder shouldn't make assumptions about whether its user is a human or Gridsync.

(But, yeah, Gridsync shouldn't also run twice .. they will likely be the same problem you describe above with tahoe if @chris is right that it just blindly kills the offending process -- i didn't double-check this)

**Comment by crwood** [comment]
Gridsync will _not_ run twice: I use a lockfile to prevent this (such that the second instance will show a user-facing error-message refuse to continue the lock is still held by the first instance).

**Comment by meejah** [comment]
Looks like Twisted's behavior (on unix) is to refuse to start if there's a pidfile and the PID it points at exists. On windows, it does nothing (there are no pidfiles).

On unix it _checks_ for the process (I think?) by `os.kill(pid, 0)` but I don't actually know what sending signal 0 does to a process (it's not documented in `signal(7)` nor `kill(1)`).

**Comment by crwood** [comment]
>Looks like Twisted's behavior (on unix) is to refuse to start if there's a pidfile and the PID it points at exists. On windows, it does nothing (there are no pidfiles).

Thanks for confirming/checking this. I must have been operating on outdated (or just plain wrong) information above... Thanks!

**Comment by exarkun** [comment]
Using `kill` with signal 0 is how you tell if a process exists with that pid (On Linux, surprise, actually tid) or not.  It does not actually send a signal but it returns success if it could have and failure otherwise.
