### ISSUE TITLE
`magic-folder run` doesn't exit on listen error

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/magic-folder#67]
If the magic-folder daemon fails to listen on its web-port, an exception is printed but the program keeps running (and logs "successful startup"). Magic-folder should exit if this fails.

(Also, I'm not sure that the `--web-port` should be optional? It currently defaults to `tcp:9889`. Maybe a better default would be "whatever is in `magic-folder.url` if that file exists in the node-dir" or just not having a default at all (i.e. it's a required option).

**Comment by exarkun** [comment]
> (Also, I'm not sure that the --web-port should be optional? It currently defaults to tcp:9889. Maybe a better default would be "whatever is in magic-folder.url if that file exists in the node-dir" or just not having a default at all (i.e. it's a required option).

I wouldn't object to removing the default value.  Perhaps file a separate ticket for that part though.

**Comment by meejah** [comment]
Okay, filed a ticket for the second part.

**Comment by meejah** [comment]
Implemented
