### ISSUE TITLE
Document the "snapshot" format

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#702]
The format of the persistent on-grid state created by magic-folder might be written and read by different implementations (maybe different versions of magic-folder itself! or maybe entirely different implementations).

It would be helpful to have a document which serves as the canonical reference for this format, rather than having a certain revision of this implementation be the reference for this format.

This would help different implementations interoperate.  It might also help compatibility of magic-folder with itself over time.

**Comment by meejah** [comment]
This https://github.com/LeastAuthority/magic-folder/blob/main/docs/snapshots.rst gets close, but doesn't actually describe the boring bits: what directory entries go where, what is in the metadata precisely, etc.

**Comment by meejah** [comment]
The above is missing the context: how are Snapshots represented inside the wider structure of the Collective and Personal mutables (which have their own metadata too).
