### ISSUE TITLE
tahoe changes break magic-folder

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/magic-folder#86]
The "remove magic-folder" PR that got merged into Tahoe recently has I think broken us (because it removes `eliotutil`). See, e.g., https://circleci.com/gh/LeastAuthority/magic-folder/4687

**Comment by meejah** [comment]
Oh, also it seems like `eliot` doesn't have `eliot._action._context` anymore, which ends up breaking a bunch of stuff in the "old" Tahoe `eliotutil.py` (that I tried copying in to magic-folder to make stuff work) ...

**Comment by vu3rdd** [comment]
Closed by https://github.com/LeastAuthority/magic-folder/pull/87
